# 服务端口
server:
  port: 8080

# spring配置
spring:
  application:
    name: sharding5-nacos-demo
  profiles:
    active: dev

# 打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core: DEBUG