# 服务端口
server:
  port: 8080
# 数据库配置(普通数据源)
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/store_db?useUnicode=true
#    username: root
#    password: root

# sharding配置
sharding:
  file: sharding-jdbc.yaml

# 数据库配置(sharding数据源)
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:${sharding.file}

# 打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core: DEBUG